[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.madrid2020]
  command = "hugo --gc --minify -b $URL --environment $HUGO_ENV"
  publish = "public"

[context.madrid2020.environment]
  HUGO_ENV = "madrid2020"
  HUGO_VERSION = "0.55.6"
  HUGO_ENABLEGITINFO = "true"